os: linux


dist: trusty


env:
  global:
    - RUN_SONAR_SCANNER=0


language: php


addons:
  chrome: stable
  sonarcloud:
    organization: "medicalmundi"
    token: $SECRET_SONAR_TOKEN


cache:
  directories:
  - $HOME/.composer/cache


.steps:
  #
  #   CI STEP
  #
  - &add-composer-bin-dir-to-path |
      export PATH="$PATH:$HOME/.composer/vendor/bin"

  - &disable-xdebug-php-extension |
      phpenv config-rm xdebug.ini || echo "xdebug not available"

  - &disable-php-memory-limit |
      echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  - &install-project-dependencies |
      composer install --no-progress --no-suggest --ansi

  - &lint-composer |
      composer validate --no-check-publish --no-check-lock --ansi -vvv

  - &run-phpunit-tests-with-coverage |
      ./vendor/bin/phpunit --colors=always --coverage-clover=coverage-report.clover --log-junit=test-report.xml

  - &run-phpunit-tests |
      ./vendor/bin/phpunit --colors=always

  - &run-code-style-check |
      ./vendor/bin/php-cs-fixer fix --dry-run -v


jobs:
  include:
    - name: '(PHP 7.2)'
      php: '7.2'
      env: RUN_SONAR_SCANNER=1
      before_install:
        - *disable-php-memory-limit
      install:
        - *install-project-dependencies
      before_script:
        - *lint-composer
      script:
        - *run-code-style-check
        - *run-phpunit-tests-with-coverage
      after_success:
        - if [[ $RUN_SONAR_SCANNER == "1" ]]; then sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.projectVersion=$TRAVIS_TAG; fi

    - name: '(PHP 7.3)'
      php: '7.3'
      env: BUILD_ENV=7.3
      before_install:
        - *disable-php-memory-limit
      install:
        - make composer-install
      before_script:
        - composer dumpautoload
      script:
        - make check

    - name: '(PHP 7.4)'
      php: '7.4'
      env: BUILD_ENV=7.4
      before_install:
        - *disable-php-memory-limit
      install:
        - make composer-install
      before_script:
        - composer dumpautoload
      script:
        - make check
