version: '3.1'
services:
  openemr:
    volumes:
      - .:/var/www/localhost/htdocs/openemr/interface/modules/custom_modules/oe-modules-todo-list
#    - ../..:/openemr:ro
#    - ../..:/var/www/localhost/htdocs/openemr:rw
#    - assetvolume:/var/www/localhost/htdocs/openemr/public/assets:rw
#    - themevolume:/var/www/localhost/htdocs/openemr/public/themes:rw
#    - sitesvolume:/var/www/localhost/htdocs/openemr/sites:rw
#    - nodemodules:/var/www/localhost/htdocs/openemr/node_modules:rw
#    - vendordir:/var/www/localhost/htdocs/openemr/vendor:rw
#    - ccdanodemodules:/var/www/localhost/htdocs/openemr/ccdaservice/node_modules:rw
#    - logvolume:/var/log
#    - couchdbvolume:/couchdb/data
